name: TECHNOVISION - LiteManager RDP by TRX

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Windows RDP VM
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Download and Run Setup
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/ali23gj/RDP/main/Downloads.bat" -OutFile "Downloads.bat"
          ./Downloads.bat

      - name: Show Access Info
        shell: cmd
        run: cmd /c show.bat

      - name: Keep Service Running
        shell: cmd
        run: cmd /c loop.bat
